Gabeaws/jenkins/complete example
aws-games/cloud-game-development-toolkit pull request #240
Opened 2024-09-04 21:12 UTC by gabebatista

**Issue number:** 176

## Summary

Adds simple, but complete, example of deploying Jenkins on its own.

### Changes

Adds simple, but complete, example of deploying Jenkins on its own.
Fixes Jenkins Route53 record name to properly align with certificate

### User experience

Users now have a simple example demonstrating how to deploy Jenkins on its own

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented

<details>
<summary>Is this a breaking change?</summary>
No
</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created might not be successful.

2024-09-06 16:53 UTC, henrykie requested changes
Couple of comments to resolve, but overall it looks good.

Make these changes, and then commit these updates with the following message:

feat(jenkins example): Adding simple example deployment of Jenkins for automated testing

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/dns.tf
> +# }
Lets remove this

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/dns.tf
> +  domain_name       = "jenkins.${data.aws_route53_zone.root.name}"
lets reference the `aws_route53_record.jenkins.name` field for this instead

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/dns.tf
> +# tflint-ignore: terraform_required_providers
Whats up with this? We should include a versions.tf or providers.tf file inside the sample that specifies which versions of the provider are used. dependabot will keep these up to date.

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/local.tf
> +  fully_qualified_domain_name = "example.com" # update this to the root domain name you own
Lets shift these two variables please. fully_qualified_domain_name should be a variable that is injected at apply time.

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/local.tf
> +  allowlist = []
remove

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/local.tf
> +  allowlist = []
If tflint is telling us its unused, then we can remove it

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/local.tf
> +}
Keep all of this, but wipe the other locals. Move fully_qualified_domain_name to a variable injected at runtime. That way we can actually automate deployments into a hosted zone we've created ahead of time in the CI account.

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/main.tf
> +# tflint-ignore: terraform_required_version
Same thing here. Its telling you to specify which versions of the provider you are using. That way we don't have samples / examples on multiple versions of the provider.

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/vpc.tf
> +}
Its funny to me that its still alarming on this... When you run the precommit checks does this flag? Or is it only on the GH side?

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/vpc.tf
> +  vpc_id = aws_vpc.build_pipeline_vpc.id
Can we rename the resources that are `build_pipeline` specific to things that are more focused on this "jenkins" specific example? Its the `jenkins_vpc` in this context.

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/vpc.tf
> +      Name = "build-pipeline-igw"
Same thing as above - naming.

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/vpc.tf
> +      Name = "build-pipeline-public-rt"
naming

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/vpc.tf
> +      Name = "build-pipeline-nat-eip"
naming

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/vpc.tf
> +}
Does this flag on precommit?

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/vpc.tf
> +      Name = "build-pipeline-private-rt"
naming

2024-09-06 16:53 UTC, henrykie commented on modules/jenkins/examples/complete/vpc.tf
> +      Name = "build-pipeline-nat"
naming

2024-09-12 19:56 UTC, gabebatista commented on modules/jenkins/examples/complete/vpc.tf
> +}
I didn't see in the precommit, so it's GH only

2024-09-12 19:56 UTC, gabebatista commented on modules/jenkins/examples/complete/vpc.tf
> +}
This also didnt come up as an issue on the precommit.

2024-09-12 20:19 UTC, gabebatista commented on modules/jenkins/examples/complete/dns.tf
> +  domain_name       = "jenkins.${data.aws_route53_zone.root.name}"
This change causes a `Cycle` error.
![Screenshot 2024-09-12 at 4 19 01 PM](https://github.com/user-attachments/assets/353a22d7-16d2-44b1-b479-7334cb563422)

2024-09-12 20:56 UTC, henrykie submitted a review, later dismissed

2024-09-13 08:20 UTC, jorisdon requested changes

2024-09-13 08:20 UTC, jorisdon commented on modules/jenkins/examples/complete/versions.tf
> +      version = "5.62.0"
This needs to match the version in `modules/jenkins/versions.tf` or else `terraform init` fails with:
```
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/aws: no available releases match the given constraints 5.62.0, 5.66.0
```

2024-09-13 08:20 UTC, jorisdon commented on modules/jenkins/examples/complete/variables.tf
> +  default     = null
Probably a good idea to make the user explicitly provide this, or provide a better default.
Currently, this default causes an error:
```
│ Error: Invalid function argument
│
│   on ..\..\iam.tf line 75, in data "aws_iam_policy_document" "jenkins_default_policy":
│   75:     for_each = length(var.jenkins_agent_secret_arns) > 0 ? [1] : []
│     ├────────────────
│     │ while calling length(value)
│     │ var.jenkins_agent_secret_arns is null
```

2024-09-13 08:20 UTC, jorisdon commented on modules/jenkins/examples/complete/variables.tf
> +  description = "The fully qualified domain name (FQDN) to be used for jenkins"
The FQDN here should NOT be prefixed with "jenkins." correct? As the sample takes care of that elsewhere? If so, might be a good idea to clarify this in the description.

2024-09-13 08:20 UTC, jorisdon commented on modules/jenkins/examples/complete/variables.tf
> +  default     = null
Defaulting this to `[]` works

2024-09-13 14:12 UTC, jorisdon submitted a review, later dismissed

2024-09-24 17:28 UTC, henrykie approved these changes

2024-09-24 17:31 UTC, merged