Henrykie/helix swarm
aws-games/cloud-game-development-toolkit pull request #306
Opened 2024-09-23 02:19 UTC by henrykie

**Issue number:**
closes #41 
closes #294 

## Summary

General improvements to the Perforce Helix Swarm module, and Perforce Helix Swarm example configurations.

### Changes

> Please provide a summary of what's being changed

= Replace Redis sidecar container with Elasticache.
= Adds SSO enable flag to Helix Swarm module.
- Minor changes to formatting on HAS module.
- Adds example configuration that provisions Helix Core, Helix Swarm, and Helix Authentication Service.

### User experience

> Please share what the user experience looks like before and after this change

- Users should specify `enable_sso` to configure Swarm to use the SSO login page.
- Redis is no longer configured as a sidecar in the Helix Swarm module. Instead, Helix Swarm now uses an Elasticache cluster it provisions itself. If you would like to use an external redis connection this can be passed through the `existing_redis_connection` variable.
- Users can refer to the "complete" example under the Perforce module for a Helix Core, Helix Swarm, Helix Authentication Service configured deployment.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [ ] Changes are documented

<details>
<summary>Is this a breaking change?</summary>

Yes. This does replace the existing Redis sidecar container in the Helix Swarm module with a dedicated Elasticache cluster.

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created might not be successful.

2024-09-27 17:04 UTC, gabebatista approved these changes
lgtm, made some minor comments on naming standard for fqdn prefix

2024-09-27 17:04 UTC, gabebatista commented on modules/perforce/examples/complete/main.tf
> +  fqdn                            = "https://auth.helix.${var.root_domain_name}"
You used `core.helix.perforce.${var.root_domain_name}` for helix core, so should this one be `auth.helix.perforce.${var.root_domain_name}` to keep the naming standard?

2024-09-27 17:25 UTC, kylesomers requested changes
see inline comments. small fixes

2024-09-27 17:25 UTC, kylesomers commented on docs/media/images/helix-swarm-architecture.jpg
Cut dimensions in half. Renders really large in the docs

2024-09-27 17:25 UTC, kylesomers commented on modules/perforce/helix-authentication-service/main.tf
> +          name  = "TRUST_PROXY"
What's going on here with the spacing?

2024-09-27 17:33 UTC, henrykie commented on modules/perforce/helix-authentication-service/main.tf
> +          name  = "TRUST_PROXY"
Formatting. My machine aligns spacing for fields in the same block. Other folks do not. We need to add a prettier config.

2024-09-27 17:33 UTC, henrykie commented on docs/media/images/helix-swarm-architecture.jpg
Understood.

2024-09-27 17:33 UTC, henrykie commented on docs/media/images/helix-swarm-architecture.jpg
Will fix.

2024-09-27 17:34 UTC, henrykie commented
@jorisdon @gabebatista @kylesomers I've made changes to the actual commit history on this branch to match Joris's git strategy as discussed. Individual commits can be reviewed as discrete pieces (swarm updates, core updates, etc...). This makes reviews easier. It also allows us to rebase the feature branch onto main and have each of these commits show up in changelog.

2024-09-27 21:32 UTC, henrykie commented on modules/perforce/examples/complete/main.tf
> +  fqdn                            = "https://auth.helix.${var.root_domain_name}"
Good catch. I will adjust.

2024-09-30 20:17 UTC, jorisdon submitted a review, later dismissed
LGTM

2024-09-30 20:17 UTC, jorisdon commented on docs/modules/perforce/examples/complete.md
> +This example provisions [Helix Core](https://www.perforce.com/products/helix-core), [Helix Swarm](https://www.perforce.com/products/helix-swarm), and the [Helix Authentication Service](https://www.pe
typo fix: variabl -> variable

2024-09-30 22:18 UTC, kylesomers approved these changes

2024-09-30 23:32 UTC, merged