Unreal Engine Horde Module
aws-games/cloud-game-development-toolkit pull request #330
Opened 2024-09-29 04:54 UTC by henrykie

**Issue number:**
Closes #11
Addresses #326

## Summary

First version of the Unreal Engine Horde module.

This module provisions the following resources:
- Unreal Engine Horde service on Elastic Container Service powered by AWS Fargate
- Amazon Elasticache with Redis OSS cluster for Horde server
- Amazon DocumentDB cluster for Horde server
- Configurable autoscaling groups to be registered as Horde agents
- SSM Command Document and Ansible playbook for configuring Ubuntu + AL2023 machines as Horde agents
- Security groups, IAM roles, various supporting resources

### Changes

Net new module.

> Please provide a summary of what's being changed

This version provides an easy deployment path for the Unreal Engine Horde CI/CD system on AWS. It can be used to configure the Horde server and N autoscaling groups of agents.

### User experience

> Please share what the user experience looks like before and after this change

Horde server deployment now available.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented

<details>
<summary>Is this a breaking change?</summary>

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created might not be successful.

2024-09-30 21:09 UTC, jorisdon requested changes
Looks great already! Left a few small comments on things to improve.

2024-09-30 21:09 UTC, jorisdon commented on modules/unreal/horde/variables.tf
> +    "IAC_PROVIDER"   = "Terraform"
use all-lowercase tag names

2024-09-30 21:09 UTC, jorisdon commented on modules/unreal/horde/variables.tf
> +}
This is neat and something we should probably do elsewhere as well! :thumbsup:

2024-09-30 21:09 UTC, jorisdon commented on modules/unreal/horde/variables.tf
> +  description = "The preferred window for DocumentDB backups to be created."
Worth noting perhaps that this is in UTC

2024-09-30 21:09 UTC, jorisdon commented on modules/unreal/horde/docdb.tf
> +resource "aws_docdb_cluster" "horde" {
Might be a good idea to also include (variables for) [backup_retention_period](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_cluster#backup_retention_period) and [preferred_maintenance_window](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_cluster#preferred_maintenance_window)

2024-10-01 01:27 UTC, kylesomers approved these changes

2024-10-01 01:29 UTC, kylesomers approved these changes

2024-10-01 01:30 UTC, merged