initial commit of unreal cloud ddc module and sample
aws-games/cloud-game-development-toolkit pull request #341
Opened 2024-10-03 16:35 UTC by danielw-aws

**Issue number:**

## Summary

Added single region example and Unreal Cloud DDC modules to CGD

### Changes

> Added files to instantiate and deploy Unreal Cloud DDC

### User experience

> Nothing has changed except adding two modules for unreal cloud DDC

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] I have performed a self-review of this change
* [ ] Changes have been tested
* [ ] Changes are documented

<details>
<summary>Is this a breaking change? No</summary>

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created might not be successful.

2024-10-03 19:45 UTC, henrykie requested changes
Lets grab some time and you can explain a lot of the little nit-picky things. Generally looks really good!

2024-10-03 19:45 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
I've seen this variable a couple of places. We should standardize the way we manage domain name specification for inter application communication / routing across samples / examples.

2024-10-03 19:45 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
Again, lets manage access external to modules.

2024-10-03 19:45 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-intra-cluster/data.tf
> +  }
Whats this permission for?

2024-10-03 19:45 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-intra-cluster/data.tf
> +  }
Why is the module creating records? Can we do this at the sample level? You can't ensure that they use Route53 for DNS.

2024-10-03 19:45 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-intra-cluster/data.tf
> +  }
This one too feels iffy. What are the R53 permissions for?

2024-10-03 19:45 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-intra-cluster/main.tf
> +}
Can you try and provide a good reason why we want to do this externally instead of using default provider to create roles / policies?

2024-10-03 19:45 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-intra-cluster/main.tf
> +}
Please elaborate on this. cert manager is used for intra node communication?

2024-10-03 19:45 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-intra-cluster/main.tf
> +}
@danielw-aws we should not allow override on the external module checks. This opens us up to supply-chain infra issues.

2024-10-03 19:45 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-intra-cluster/outputs.tf
@danielw-aws lets remove outputs.

2024-10-03 19:45 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-intra-cluster/variables.tf
> +}
from or for EKS cluster?

2024-10-03 19:45 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-intra-cluster/variables.tf
> +}
What are these for? How do they get used?

2024-10-03 19:46 UTC, henrykie commented
Your most recent merge commit should be removed. Rebase main onto this feature branch instead. Also, signing is missing on the first commit.

2024-10-04 13:30 UTC, jorisdon commented on samples/unreal-cloud-ddc-single-region/main.tf
> +    templatefile("./assets/unreal_cloud_ddc_region_values.yaml", {
this template file is missing; is it generated or do we expect users to provide it themselves?

2024-10-04 13:30 UTC, jorisdon commented on samples/unreal-cloud-ddc-single-region/main.tf
> +    templatefile("./assets/unreal_cloud_ddc_base.yaml", {
this template file is missing; is it generated or do we expect users to provide it themselves?

2024-10-04 21:04 UTC, gabebatista reviewed
I think Henry hit most of the important points. Added some comments for minor things.

2024-10-11 18:36 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/vpc/main.tf
> +      "kubernetes.io/role/elb" = 1
Allows the subnet to be used for a public load balancer. Reference: https://repost.aws/knowledge-center/eks-vpc-subnet-discovery

2024-10-11 19:32 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/main.tf
> +}
@danielw-aws please include explanation with checkov suppression comments

2024-10-11 20:57 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/vpc/versions.tf
> +      version = ">= 5.38"
Bumped all versions of providers in the module (TLS, Helm, Kubernetes)
Will add in a forth coming commit

2024-10-11 21:33 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/variables.tf
> +}
Sure. Would it be better to call call it eks_cluster_ip_allow_list?

2024-10-11 21:55 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/providers.tf
> +      args        = ["eks", "get-token", "--cluster-name", module.unreal_cloud_ddc_infra.cluster_name, "--output", "json", "--profile", var.profile]
This comes from the official terraform documentation. https://developer.hashicorp.com/terraform/tutorials/kubernetes/helm-provider. I just replaced the data block with a module since it was an out put.

2024-10-11 21:56 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/providers.tf
> +      args        = ["eks", "get-token", "--cluster-name", module.unreal_cloud_ddc_infra.cluster_name, "--output", "json", "--profile", var.profile]
previous link was helm this is kubernetes https://developer.hashicorp.com/terraform/tutorials/kubernetes/kubernetes-provider?variants=kubernetes%3Aeks

2024-10-15 18:25 UTC, kylesomers commented on modules/unreal/unreal-cloud-ddc-infra/main.tf
What's the EKS versioning plan for this module? What prevents you from using latest EKS version (1.31 I believe)? I'd like to see a runbook of steps for testing the module before we release this. If game devs will take a dependency on this module then we don't want our trailing EKS versioning to be a reason they cannot update their clusters to latest version or need to incur additional cost for EKS extended support for older version.

2024-10-15 18:26 UTC, kylesomers requested changes
Already some great feedback from others in here. For me, biggest question is EKS versioning and how we want to handle this. What prevents you from using latest EKS version (1.31 I believe)? I'd like to see a runbook of steps for testing the module for EKS version compatibility before we release this. If game devs will take a dependency on this module then we don't want our trailing EKS versioning to be a reason they cannot update their clusters to latest version or need to incur additional cost for EKS extended support for older version.

2024-11-07 01:13 UTC, henrykie commented
@danielw-aws you need to address the existing requested changes (close out conversations) and re-request reviews for this. We're still failing checkov as well :)

2024-11-07 22:24 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-intra-cluster/main.tf
> +}
removed this

2024-11-07 22:44 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/variables.tf
> +}
Changed the name as its supposed to be for allow listing

2024-11-07 22:45 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/providers.tf
> +    api_version = "client.authentication.k8s.io/v1beta1"
comes from the documentation

2024-11-13 15:25 UTC, henrykie commented
@danielw-aws any updates here that you want me to review?

2024-11-25 23:19 UTC, henrykie requested changes
More updates to address - include comments ASAP, and we can divy up what needs to be fixed. I'll hop on this as well.

2024-11-25 23:19 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +# }
Please remove unused resources

2024-11-25 23:19 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/outputs.tf
> +}
This needs to be a static field:

``` terraform
output "peer_security_group_id" {
  value = aws_security_group.scylla_security_group.id
}
```

2024-11-25 23:19 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/route53.tf
> +}
One concern is this module depends heavily on access to the existing VPC. What if DNS / VPC is managed in a different account? How will these resources have the access they need? For example, cross-account VPC / R53 zone association is non-trivial. We do not currently provide that flexibility.

2024-11-25 23:19 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/sg.tf
> +# }
Remove unused resources

2024-11-25 23:19 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +# }
Remove unused variables

2024-11-25 23:19 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
Include a `validation` block if there are constraints here.

2024-11-25 23:19 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-intra-cluster/helm.tf
> +  #checkov:skip=CKV_AWS_356:Ensure no IAM policies documents allow "*" as a statement's resource for restrictable actions
Again, explanations please :)

2024-11-25 23:19 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-intra-cluster/helm.tf
> +  enable_aws_cloudwatch_metrics       = true
Required? Or can we parameterize?

2024-11-25 23:19 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-intra-cluster/helm.tf
> +    }
Required? Or can we parameterize?

2024-11-25 23:19 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-intra-cluster/variables.tf
> +  default     = "1.2.0"
Do you want to do conditional validation on this? Is there a minimum version that works?

2024-11-25 23:19 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-intra-cluster/variables.tf
> +  description = "Arn for oidc credentials stored in secret manager."
I am not sure what this is for - is this external IDP access to the DDC API?

2024-11-25 23:19 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-intra-cluster/variables.tf
> +  description = "Arn for credentials stored in secret manager. Needs to be prefixed with 'ecr-pullthroughcache/' to be compatible with ECR pull through cache."
Add validation to ensure that the pullthroughcache/ prefix exists.

2024-11-25 23:19 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/main.tf
>    vpc_cidr              = "192.168.0.0/23"
Funny cidr decision on this one... Do we want to use something simpler?

2024-11-25 23:19 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/main.tf
> +  eks_cluster_access_cidr = var.eks_cluster_ip_allow_list
Is this to have external API access? If so, I would recommend exposing the security group for the cluster as an output, and then creating the requisite rules to grant external access at the sample level instead.

2024-11-25 23:19 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/main.tf
> +    templatefile("./assets/unreal_cloud_ddc_base.yaml", {
It still sits in `modules/unreal/samples/unreal-cloud-ddc-single-region/assets` instead of the root `assets` directory. I presume we still think it should migrate higher up?

2024-11-25 23:19 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/main.tf
> +      scylla_dns          = "scylla.example.com"
This is an internal private hosted zone created BY the module. I also see a problem with this in situations where networking is handled by a distinct account from the DDC deployment account (cross-account VPC hosted zone association)

2024-11-25 23:19 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/main.tf
> +      jwt_authority       = jsondecode(data.aws_secretsmanager_secret_version.current.secret_string)["jwt_authority"]
I am confused by this block.

2024-11-25 23:19 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/main.tf
>      file("./assets/unreal_cloud_ddc_values.yaml")
would rather see us use the [Terraform path object](https://developer.hashicorp.com/terraform/language/expressions/references#filesystem-and-workspace-info)

2024-11-25 23:19 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/variables.tf
>  }
Better description and instructions for creating this secret

2024-11-25 23:19 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/variables.tf
>    description = "IPs that will be allow listed to access cluster over internet"
I think this should be managed externally. Cluster SG ID is output from the module. Rules are created at the sample level.

2024-11-26 21:17 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +  #checkov:skip=CKV_AWS_38:IP restriction set in module variables
fixed these comments

2024-11-26 21:17 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +  retention_in_days = 365
done

2024-11-26 21:18 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +  #checkov:skip=CKV_AWS_341:Ensure Launch template should not have a metadata response hop limit greater than 1
this was a legacy of an issue i was trying to debug which turned out to be something else. Removed this and made it standard in the launch template.

2024-11-26 21:36 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/variables.tf
>    description = "IPs that will be allow listed to access cluster over internet"
So this is so terraform can set up the eks cluster. if this is not enabled we have to have a server or bastion running in a private subnet which is hard to showcase with an example. Lets talk about how to fix this

2024-11-26 22:28 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +}
@henrykie

2024-11-26 22:28 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +}
@henrykie

2024-11-26 22:31 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +}
As long as the access is restricted by SG and defaulted to empty access we can suppress this.

2024-12-20 23:33 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +  enabled_cluster_log_types = ["api", "audit", "authenticator", "controllerManager", "scheduler"]
Done

2024-12-20 23:35 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +  #checkov:skip=CKV_AWS_341:Ensure Launch template should not have a metadata response hop limit greater than 1
NVMe doesnt require hop limit of 2 but system does for load balancer controller set up. Updated comment and removed checkov skips from non-required asssets

2024-12-20 23:36 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +    http_put_response_hop_limit = 2
Required for load balancer controller.

2024-12-20 23:36 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +    http_put_response_hop_limit = 2
done

2024-12-20 23:36 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +# }
Removed

2024-12-20 23:36 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/route53.tf
> +}
I got this working with ips so this is now removed.

2024-12-20 23:37 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/sg.tf
> +# }
removed

2024-12-20 23:37 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
fixed the constraints and should work with any supported version of kubernetes

2024-12-20 23:50 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/providers.tf
> +  }
its how we recommend to do this [example](https://docs.aws.amazon.com/prescriptive-guidance/latest/getting-started-terraform/providers.html)

2024-12-26 21:01 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-intra-cluster/variables.tf
> +}
This got removed as this was for a addon that was enabled. I removed the addon to limit scope.

2024-12-26 21:02 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-intra-cluster/variables.tf
> +}
This is from. Changed this variable to cluster_oidc__provider_arn

2024-12-26 21:03 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/main.tf
> +  #checkov:skip=CKV2_AWS_39:Ensure Domain Name System (DNS) query logging is enabled for Amazon Route 53 hosted zones
Fixing these as I go. Ive changed some of the bigger ones but i need to do a review across all of the comments to update.

2024-12-26 21:07 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/main.tf
> +    templatefile("./assets/unreal_cloud_ddc_region_values.yaml", {
Added this in most recent commits

2024-12-26 21:08 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/main.tf
> +# ################################################################################
Removed most of these and cleaned them up

2024-12-26 21:10 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
Fixed this in an upcoming commit. These are defined as subnet ids and clarified the comment to reflect this.

2024-12-26 21:21 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +  subnet_ids      = var.private_subnets
Updated in a future commit.

2024-12-26 21:26 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +    min_size     = 1
Parameterized all of them

2024-12-26 21:26 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +    min_size     = 1
Parameterized.

2024-12-26 21:40 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/variables.tf
>  }
I removed this cause the interpolation doesnt work outside of okta.

2024-12-30 17:42 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/main.tf
>    vpc_cidr              = "192.168.0.0/23"
changing to /24

2024-12-30 18:57 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/variables.tf
>  }
Putting this into the read me

2025-01-02 21:55 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
these dont i can make variables for this but best practices says it should be

2025-01-02 21:58 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/outputs.tf
Added

2025-01-02 21:59 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
I have a data block that does a look up of this. I can move this to the forefront to show how to get the standard image then just consume the AMI

2025-01-02 22:21 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
Changed these to i3en.large as the default

2025-01-02 22:25 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
Yes. I4G is an option

2025-01-02 22:27 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
In a best practice both should be behind private subnets. DB should not be accessible and the worker is replicating requests across a vpc peer.

2025-01-02 22:27 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
Originally i had this as a self contained way to have to regions with seperate cidr blocks that would be fully enabled for each other. Im open to discussing this.

2025-01-02 22:28 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
This was removed. It works without a dns name.

2025-01-02 22:28 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
This is needed to configure the cluster for the helm chart and is seperate from the vpc replication.

2025-01-02 22:29 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-intra-cluster/data.tf
> +  }
Load Balancer controller via AWS EKS Blueprints

2025-01-02 22:37 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/main.tf
>    vpc_cidr              = "192.168.0.0/23"
Originally this was going to be two cidr ranges right next to each other to showcase a multi region deployment.

2025-01-02 22:38 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/main.tf
> +  system_managed_node_desired_size  = 1
Yes. Workers are only set up to replicate between multiple regions through speculative replication. Because this is a single region i have no need for a worker.

2025-01-02 22:39 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/main.tf
> +    templatefile("./assets/unreal_cloud_ddc_base.yaml", {
Ive added these to the next commit.

2025-01-02 22:40 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/local.tf
> +}
When it ran previously it was picking these up. I had to hard code these to remove none viable AZs.

2025-01-02 22:49 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
Best practice says these are private.

2025-01-02 22:50 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-intra-cluster/data.tf
> +  }
This was for cert manager this has since been removed

2025-01-02 22:51 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-intra-cluster/data.tf
> +  }
This was for cert manager it has been removed.

2025-01-02 22:51 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-intra-cluster/data.tf
> +  }
this was removed and was part of eks blueprint cert manager requirements

2025-01-02 22:54 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/providers.tf
> +  cluster_ca_certificate = base64decode(module.unreal_cloud_ddc_infra.cluster_certificate_authority_data)
Its the public key of the cluster and how we recommend interacting with a cluster [example](https://docs.aws.amazon.com/prescriptive-guidance/latest/getting-started-terraform/providers.html)

2025-01-02 22:56 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/main.tf
>      file("./assets/unreal_cloud_ddc_values.yaml")
Changed in a upcoming commit to path

2025-01-02 22:57 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/main.tf
> +      jwt_authority       = jsondecode(data.aws_secretsmanager_secret_version.current.secret_string)["jwt_authority"]
This was interpolating a secrets manager json object to be used in the sample. Lets talk about this

2025-01-03 18:51 UTC, henrykie approved these changes
Minor adjustments, typos, defaults. Looks good!

2025-01-03 18:51 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +    http_put_response_hop_limit = 1
Comment explaining this

2025-01-03 18:51 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +    http_put_response_hop_limit = 1
same here

2025-01-03 18:51 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +  #checkov:skip=CKV_AWS_341:Required for the load balancer controller
What is required? "Metadata response hop limit must be greater than 1 for LB controller"

2025-01-03 18:51 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/locals.tf
> +      "start_scylla_on_first_boot" : false
Why are we setting this to false?

2025-01-03 18:51 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
>  }
Is this used for access to public endpoint to configure the cluster?

2025-01-03 18:51 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +    condition     = (var.nvme_managed_node_min_size <= var.nvme_managed_node_desired_size) && (var.nvme_managed_node_desired_size <= var.nvme_managed_node_max_size)
Eventually we should look to leverage the hashicorp/assert provider's [`between`](https://registry.terraform.io/providers/hashicorp/assert/latest/docs/functions/between) function eventually

Larger RFC around validations for variables and variable names? RFC around using provider specified functions?

2025-01-03 18:51 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +  description = "A list of private subnets ids you want scylla and the EKS nodes to be installed into."
Maybe we call this `scylla_subnets` instead? And description should specify that private subnets are recommended?

2025-01-03 18:51 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/variables.tf
> +  description = "OIDC Secrets Credential ARN."
This is related to an external IDP right? This gets pulled into the Cloud DDC application layer (Helm) to enable 3P authentication.

2025-01-03 18:51 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/variables.tf
>    description = "IPs that will be allow listed to access cluster over internet"
Right - not actually passed to a security group. Used as part of [`vpc_config`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#vpc_config-1) when provisioning the cluster in `eks.tf`. See [`public_access_cidrs`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#public_access_cidrs-1) for details.

2025-01-03 18:51 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/main.tf
> +      jwt_authority       = jsondecode(data.aws_secretsmanager_secret_version.current.secret_string)["jwt_authority"]
I am okay with this as long as we call it out in documentation. It is common to have sensitive values in TF state, and from what I can tell there is not a better way to inject sensitive values into a Helm chart running on EKS.

2025-01-03 18:51 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/main.tf
> +      jwt_authority       = jsondecode(data.aws_secretsmanager_secret_version.current.secret_string)["jwt_authority"]
See [this issue](https://github.com/hashicorp/terraform-provider-helm/issues/1287) for related provider specific problem

2025-01-03 18:51 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +}
This is handled by a variable on the module. Again, as we look to support deployments both from within the VPC and externally we can consider disabling this.

2025-01-03 18:54 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/main.tf
> +      scylla_dns          = "scylla.example.com"
Scylla DNS removed (IPs instead)

2025-01-03 18:57 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/main.tf
> +      jwt_authority       = var.jwt_authority
This should not be required. These variables should be optional, and the underlying deployment of DDC should not depend on Okta specifically.

2025-01-03 18:58 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/main.tf
> +  system_managed_node_desired_size  = 1
Makes sense.

2025-01-03 19:01 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/local.tf
> +}
Huh. Lets start hardcoding which AZs we want to use in samples / examples instead. This removes randomness and improves discoverability of deployed configurations.

2025-01-03 19:06 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
You should conditionally check to make sure that `instance_type` and `scylla_architecture` agree

2025-01-03 19:07 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
Same as below - please review where subnets **must** be private. Description can always specify if subnets should be private. Plus, when you pass in subnets at the sample or example level you can pass in resources that are called `private` to drive this point home.

2025-01-07 16:39 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +  #checkov:skip=CKV_AWS_58:Secrets encryptiom will be enabled in a future update
Fixed

2025-01-07 17:39 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +    http_put_response_hop_limit = 1
Changed these as these didnt follow best practices for container environments [docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-options.html)

2025-01-07 17:39 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +    http_put_response_hop_limit = 1
See above [docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-options.html)

2025-01-07 17:41 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +  #checkov:skip=CKV_AWS_341:Required for the load balancer controller
Changed comment

2025-01-07 17:47 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/locals.tf
> +      "start_scylla_on_first_boot" : false
Added two comments to let the user know what will happen if this is set to true.

2025-01-07 17:50 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
>  }
Clarified this to eks_cluster_public_endpoint_access_cidr to ensure users know what this variable and cidr are required for,

2025-01-07 17:53 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +  description = "A list of private subnets ids you want scylla and the EKS nodes to be installed into."
Sure. As per [Scylla Documentation ](https://opensource.docs.scylladb.com/stable/operating-scylla/admin.html#admin-scylla-configuration)

> Do not expose the REST API externally for production systems.
> The following example is only for demonstration, as it exposes the REST API externally and will allow external access to administration-level information and operations on your cluster. The API is by default bound to an internal IP (127.0.0.1), blocked for external connections.

2025-01-07 18:17 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +  description = "A list of private subnets ids you want scylla and the EKS nodes to be installed into."
Broke this into two variables one for eks node groups and one for scylla.

2025-01-07 18:18 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/variables.tf
> +  description = "OIDC Secrets Credential ARN."
Changed to be external_idp_oidc_credential_arn

2025-01-07 18:20 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
two validations are now on this

> validation {
    condition     = contains(["i8g", "i7ie", "i4g", "i4i", "im4gn", "is4gen", "i4i", "i3", "i3en"], var.scylla_instance_type)
    error_message = "Must be an instance family that contains NVME"
  }
>  validation {
    condition     = contains(["arm64"], var.scylla_architecture) && contains(["i8g", "i4g", "im4gn", "is4gen"]) ||
      contains(["x86_64"], var.scylla_architecture) && contains(["i7ie", "i4i", "i4i", "i3", "i3en"])
    error_message = "Chip Architecture must match instance type"
  }

2025-01-08 22:25 UTC, henrykie requested changes

2025-01-08 22:25 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +  subnet_ids      = var.eks_node_group_private_subnets
Do these HAVE to be private?

2025-01-08 22:25 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +  subnet_ids      = var.eks_node_group_private_subnets
Do these HAVE to be private?

2025-01-08 22:25 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +  subnet_ids      = var.eks_node_group_private_subnets
Do these HAVE to be private?

2025-01-08 22:25 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/scylla.tf
> +  subnet_id = element(var.scylla_private_subnets, count.index)
Do these HAVE to be private? Or are they just the subnets where we deploy Scylla? Keep in mind, at the example / sample level you can be prescriptive. After all, you are usually passing named resources into the variables:

```terraform
module "unreal_cloud_ddc_infra" {
    source = "cloud-game-development-toolkit/modules/unreal/unreal-cloud-ddc-infra"
    ...
    scylla_subnet_ids = aws_subnet.private_subnets[*].id
    ...
}

2025-01-08 22:25 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
"A list of subnet IDs where Scylla will be deployed. Private subnets are strongly recommended."

2025-01-08 22:25 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
>  }
Optionally, you could pull this with a data block: https://stackoverflow.com/questions/46763287/i-want-to-identify-the-public-ip-of-the-terraform-execution-environment-and-add

2025-01-08 22:25 UTC, henrykie commented on samples/unreal-cloud-ddc-single-region/main.tf
> +  eks_cluster_public_access               = true
Whats the difference between these? Does this just give the cluster a private _and_ a public endpoint?

2025-01-09 16:41 UTC, danielw-aws commented on samples/unreal-cloud-ddc-single-region/main.tf
> +  eks_cluster_public_access               = true
Yes this does. As per documentation the default behavior is to have only a public endpoint but I think best practice is to have node and control plane communication go through a private channel. [Documentation](https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html#modify-endpoint-access)

2025-01-09 16:43 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
>  }
I can add that in the sample seems like an easy way to show this.

2025-01-09 16:49 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/scylla.tf
> +  subnet_id = element(var.scylla_private_subnets, count.index)
> Do not expose the REST API externally for production systems.
>The following example is only for demonstration, as it exposes the REST API externally and will allow external access to administration-level information and operations on your cluster. The API is by default bound to an internal IP (127.0.0.1), blocked for external connections.

2025-01-09 16:50 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/scylla.tf
> +  subnet_id = element(var.scylla_private_subnets, count.index)
There is no auth on these apis so no these cannot be publicly exposed

2025-01-09 17:50 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +}
Changed

2025-01-09 18:45 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/scylla.tf
> +  subnet_id = element(var.scylla_private_subnets, count.index)
They dont. I changed these all to be suggested private and updated the description. There are security groups around all of these that will protect them but ideally they are private.

2025-01-09 18:45 UTC, danielw-aws commented on modules/unreal/unreal-cloud-ddc-infra/eks.tf
> +  subnet_ids      = var.eks_node_group_private_subnets
No they dont but ideally they are

2025-01-09 20:00 UTC, henrykie commented on modules/unreal/unreal-cloud-ddc-infra/variables.tf
> +    condition     = (var.eks_cluster_public_access == true) && (length(var.eks_cluster_public_endpoint_access_cidr) > 0) && !contains(["0.0.0.0"], var.eks_cluster_public_access)
Do we need to ensure no public access (0.0.0.0)? I mean, I see what you are doing but end customers should probably be able to make that decision for themselves. @jorisdon what are your thoughts here?

2025-01-09 20:01 UTC, henrykie approved these changes
LGTM. Only one minor concern around the public access CIDR.

2025-01-31 15:18 UTC, henrykie commented
@danielw-aws can you update description on this PR and rrebase from main please

2025-02-06 23:49 UTC, henrykie approved these changes
LGTM 🚀

2025-02-07 00:00 UTC, merged