Gabeaws/docs/getting started updates
aws-games/cloud-game-development-toolkit pull request #357
Opened 2024-10-10 16:27 UTC by gabebatista

**Issue number:** 355

## Summary

Updates documentation for getting started with the simple build pipeline sample

### Changes

- added warnings regarding the region variable in packer templates as they default to `us-west-2` and can cause errors.
- Changed Packer commands to proper syntax in getting started docs
- Changed the `Note` admonition in the `Amazon Linux 2023 ARM based Amazon Machine Image` section to a warning, as not heading that admonition would cause the command to fail.
- Added defaults to the `vpc_id` and `subnet_id` variables, allowing Packer to default to the default VPC if no value is passed in.
- Renamed the `fully_qualified_domain_name` reference in`Step 5. Configure Simple Build Pipeline Variables` to `root_domain_name` to align with name change in code.
- Split `Step 5. Configure Simple Build Pipeline Variables` section into `local.tf` and `variables.tf` paragraphs to align with module structure.

### User experience

Fixes faulty code and clarifies sections which are most likely to cause issues for users.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented

<details>
<summary>Is this a breaking change?</summary>
No
</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created might not be successful.

2024-10-10 16:32 UTC, henrykie commented
closes #355 @gabebatista ?

2024-10-10 16:33 UTC, henrykie approved these changes

2024-10-11 19:09 UTC, kylesomers commented
@dependabot rebase

2024-10-14 16:08 UTC, kylesomers approved these changes

2024-10-14 17:47 UTC, kylesomers requested changes

2024-10-14 17:47 UTC, kylesomers commented on docs/getting-started.md
>  ???+ Note
This is a note not a warning, but it conveys the same warning as the one below.

2024-10-14 17:47 UTC, kylesomers commented on docs/getting-started.md
> +Configurations for the _Simple Build Pipeline_ are split between 2 files: [`local.tf`] and [`variables.tf`]. Variables in [`local.tf`] are typically static and can be modified within the file itself.
This does not render properly. fix. 
![Screenshot 2024-10-14 at 12 45 25 PM](https://github.com/user-attachments/assets/8c23068f-aac2-421b-bb52-151f0d87ffd7)

2024-10-16 18:59 UTC, gabebatista commented on docs/getting-started.md
>  ???+ Note
The reason I call out the region variable specifically is that this is the only one that will cause failures if left to its default value. Also the error that appears is that the subnet and/or VPC cannot be found, which can be confusing for users that are new to AWS

2024-10-16 21:26 UTC, gabebatista commented on docs/getting-started.md
> +Configurations for the _Simple Build Pipeline_ are split between 2 files: [`local.tf`] and [`variables.tf`]. Variables in [`local.tf`] are typically static and can be modified within the file itself.
Fixed

2024-10-18 14:14 UTC, jorisdon approved these changes

2024-10-18 18:04 UTC, henrykie approved these changes

2024-10-18 18:15 UTC, merged