Ochmang helixcore improvments
aws-games/cloud-game-development-toolkit pull request #378
Opened 2024-10-31 14:39 UTC by GrzesiekO

**Issue number:**
#301 #321 

## Summary

Fixed the p4_configure and added Unicode support to Helix Core.

### Changes
Minor fixes in p4_configure.sh
New variable --unicode in Terraform defaults to "false" 

> Please provide a summary of what's being changed

### User experience

New variable in terraform for helix-core module "unicode" to address unicode mode in Helix Core
New variable can be omitted then it defaults to false.
> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [ x] I have performed a self-review of this change
* [ x] Changes have been tested
* [ x] Changes are documented

<details>
<summary>Is this a breaking change?</summary>
No it is not a breaking change it fixes minor bugs and adds one core requested funcitonality
</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created might not be successful.

2024-10-31 15:04 UTC, henrykie submitted a review, later dismissed
lgtm

2024-10-31 15:04 UTC, henrykie commented on assets/packer/perforce/helix-core/p4_configure.sh
> +# update label for selinux -> This should be optional as by deualt in Amazon Linux selinux is disabled - Permissive
nit typo

2024-10-31 15:06 UTC, jorisdon submitted a review, later dismissed

2024-10-31 15:12 UTC, henrykie commented
@GrzesiekO please rebase the base branch onto this feature branch, and potentially consider renaming / squashing your second commit so that both use conventional commit structure.

2024-11-07 01:13 UTC, henrykie commented
@GrzesiekO You want to update and merge?

2024-11-13 16:41 UTC, jorisdon submitted a review, later dismissed

2024-11-13 17:17 UTC, henrykie requested changes
Please respond to comments. We do not need to fix these issues immediately, but should track them.

2024-11-13 17:17 UTC, henrykie commented on assets/ansible-playbooks/perforce/helix-core/p4_configure_playbook.yml
We should adopt a naming convention for playbooks so that IDEs can detect that they are ansible. Some look for a "playbooks" directory, others accept a .ansible.yml or .playbook.yml file suffix.

2024-11-13 17:17 UTC, henrykie commented on assets/ansible-playbooks/perforce/helix-core/ssm_module.tf
> +
nit: we should get prettier setup for formatting consistency.

2024-11-13 17:17 UTC, henrykie commented on assets/ansible-playbooks/perforce/helix-core/ssm_module.tf
> +}
variables should be defined separately. Why. is this a variable?

2024-11-13 17:17 UTC, henrykie commented on assets/ansible-playbooks/perforce/helix-core/ssm_module.tf
> +}
As discussed this should be abstracted to a separate asset. Commenting for posterity's sake.

2024-11-13 17:17 UTC, henrykie commented on assets/ansible-playbooks/perforce/helix-core/ssm_module.tf
> +resource "aws_ssm_association" "toolkitdoc" {
nit: naming convention - `toolkitdoc` is not adequate.

2024-11-13 17:17 UTC, henrykie commented on assets/ansible-playbooks/perforce/helix-core/ssm_module.tf
> +      "path" = "https://s3.amazonaws.com/${var.s3_bucket_name}/${var.playbook_file_name}"
check out [`aws_s3_bucket.example.bucket_domain_name`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#bucket_domain_name-1) as an attribute. No need to reference the var here - we can put a dependency on the created bucket's domain name.

2024-11-13 17:17 UTC, henrykie commented on assets/ansible-playbooks/perforce/helix-core/ssm_module.tf
> +    values = ["ToolkitTest"]
nit: naming

2024-11-13 17:17 UTC, henrykie commented on assets/packer/perforce/helix-core/p4_configure.sh
> +# restorecon -vF /p4/1/bin/p4d_1_init
We've commented it out but not made it optional?

2024-11-15 14:52 UTC, jorisdon commented on assets/packer/perforce/helix-core/p4_configure.sh
> +# restorecon -vF /p4/1/bin/p4d_1_init
Good idea; I've updated this so it's configurable instead.

2024-11-15 14:52 UTC, jorisdon commented on assets/packer/perforce/helix-core/p4_configure.sh
> +    echo "  --selinux <true/false>   Update labels for SELinux"
nit: Inconsistency in parameters between these 3 parameters (true/false vs 0/1). All of these parameters are driven by Terraform (ec2 userdata) so it's not a big issue, but it'd be good to have this consistent.

2024-11-15 14:52 UTC, henrykie submitted a review, later dismissed

2024-11-15 14:53 UTC, henrykie commented on assets/packer/perforce/helix-core/p4_configure.sh
> +    echo "  --selinux <true/false>   Update labels for SELinux"
I'd love to just see it be existence based, but its up to @GrzesiekO

2024-11-15 14:56 UTC, jorisdon commented on assets/ansible-playbooks/perforce/helix-core/ssm_module.tf
> +resource "aws_ssm_association" "toolkitdoc" {
fixed

2024-11-15 14:57 UTC, jorisdon commented on assets/ansible-playbooks/perforce/helix-core/ssm_module.tf
> +    values = ["ToolkitTest"]
fixed, though I'm not sure where this tag value gets set

2024-11-15 15:06 UTC, jorisdon commented
I am not entirely sure how this Ansible playbook and the Packer template are supposed to be used. Do we expect users to build the Perforce AMI via Packer (which loads `p4_configure.sh` onto the AMI) and then later on install Perforce Helix Core through the Ansible playbook?

2024-11-15 15:08 UTC, henrykie commented
+1. I was under the impression we were eventually _replacing_ `p4_configure.sh` with `configure_helix_core.playbook.yml` or something like that. Then we would just invoke it on startup via an SSM association instead of using user data...

2024-11-28 15:08 UTC, jorisdon commented on assets/ansible-playbooks/perforce/helix-core/p4_configure_playbook.yml
good idea; `.ansible.yml` would be what I'd propose.
The playbook has been removed from this branch, so I'll resolve this conversation.

2024-11-28 15:09 UTC, jorisdon commented on assets/ansible-playbooks/perforce/helix-core/ssm_module.tf
> +
Agreed. `ssm_module.tf` has been removed from this branch so I'm resolving this comment.

2024-11-28 15:10 UTC, jorisdon commented on assets/ansible-playbooks/perforce/helix-core/ssm_module.tf
> +}
`ssm_module.tf` has been removed from this branch and will be introduced in a future branch when the Ansible deployment mechanism is introduced in a separate PR. Resolving this comment, though we should not forget about this comment when we re-introduce it.

2024-11-28 15:29 UTC, jorisdon commented on assets/packer/perforce/helix-core/p4_configure.sh
> +    echo "  --selinux <true/false>   Update labels for SELinux"
Yeah, good point. As this is 'internal' and gets called via EC2 userdata, I don't think it matters too much; we can clean it up and align it with the `--case_sensitive` flag later in a separate PR.

2024-11-28 15:33 UTC, jorisdon approved these changes
Contents LGTM, though we should squash and merge this PR or clean up commit history for this (I don't recommend using rebase and merge at the moment)

2024-11-28 17:57 UTC, henrykie approved these changes

2024-11-28 17:57 UTC, henrykie commented on assets/packer/perforce/helix-core/p4_configure.sh
> +    echo "  --selinux <true/false>   Update labels for SELinux"
Sure - but the whole point is you can always JUST use the script. Or the playbook. Or the template. So I think it does matter. Agreed we can save for a new issue.

2024-11-28 17:59 UTC, merged