chore: add external tls access to ALB + force cleanup resource flag
aws-games/cloud-game-development-toolkit pull request #383
Opened 2024-11-05 01:01 UTC by stephenlacy

I noticed that the horde example stack doesn't have internet access through the ALB due to the security group rules.
Also added a enable_force_cleanup variable to cleanup s3 buckets.

## Summary

### Changes
- Adds a flag to enable a clean stack deletion
- Enables public access to the horde server running on :443

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [ ] Changes are documented

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created might not be successful.

2024-11-07 01:12 UTC, henrykie requested changes
Couple of comments! Thanks for the PR. Would be happy to get these adjustments made.

2024-11-07 01:12 UTC, henrykie commented on modules/unreal/horde/sg.tf
> +
Hey! This is deliberately closed. We didn't want to have folks unknowning deploy the sample and open their ALB to the internet. One approach could be to comment it out? Another could be to provide a variable at the sample level that can be used to configure inbound access to the ALB. This is why we expose the SG ID as an output from the module.

2024-11-07 01:12 UTC, henrykie commented on modules/unreal/horde/examples/complete/dns.tf
> +  ]
Why do we need to open up these certs for the sake of the example? Not opposed - just curious :)

2024-11-07 01:12 UTC, henrykie commented on modules/unreal/horde/variables.tf
> +
We need to make sure this propagates appropriately to the ALB listeners that are configured

2024-11-07 18:01 UTC, stephenlacy commented on modules/unreal/horde/examples/complete/dns.tf
> +  ]
This is in part to combine with the samples/ stack of having multiple sub domains on the same root domain cert rather than creating a single cert for each horde deployment.

2024-11-07 18:02 UTC, stephenlacy commented on modules/unreal/horde/sg.tf
> +
Gotcha, I added OIDC to our deployment. Will add it as a variable.

2025-01-08 18:47 UTC, gabebatista commented on modules/unreal/horde/sg.tf
> +
I agree that having a variable (which defaults to no internet access) would be good solution. We can also simply call this out in the documentation since modifying a SG is a pretty simple task. Having the ingress rule there but commented out would make it even simpler.

2025-01-08 18:49 UTC, gabebatista commented on modules/unreal/horde/variables.tf
>  }
Would it make sense to have force cleanup tied to the debug flag? Are there any use cases where we would want one without the other?

2025-01-21 17:05 UTC, henrykie commented on modules/unreal/horde/sg.tf
> +
Resolving this - required fix is to remove this ingress rule from the module. We manage these at the sample level.

2025-01-21 17:06 UTC, henrykie commented on modules/unreal/horde/variables.tf
> +
Also, the actual service is not configured to run on 443 - we handle HTTPS -> HTTP termination at the ALB level. This is something I am open to parameterizing, but would require changes in multiple places.

2025-01-21 17:08 UTC, henrykie commented
@stephenlacy there were a couple of requests for changes. We'll close this PR (happy to review again) next week unless you've got updates. Thanks!

2025-01-21 18:54 UTC, closed without merging